default_language_version:
  python: "3.11"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
-   repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config=./pyproject.toml .
        language: system
        types: [python]
      # - id: ruff
      #   name: ruff
      #   language: system
      #   entry: poetry run ruff . --fix
      #   types: [python]
